import type { NextPage } from "next";
import Head from "next/head";
import Marquee from "react-fast-marquee";

import PrimaryButton from "../components/primaryButton";
import SecondaryButton from "../components/secondaryButton";

import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NAFTA Productions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.video}>
        <video autoPlay loop muted>
          <source
            src={
              "https://res.cloudinary.com/fenkratos/video/upload/v1667063992/Nafta/MIGRANTE1_b0tmsg.mp4"
            }
            type="video/mp4"
          />
        </video>
      </div>

      <div className={styles.titleContainer}>
        <h1>
          <span className={styles.naf}>NAF</span>
          <span className={styles.ta}>TA</span>
        </h1>
      </div>

      <div className={styles.descriptionContainer}>
        <p className={styles.description}>
          WE ARE A CREATIVE PRODUCTION AGENCY DRIVING CHANGE ACROSS BORDERS.
          FROM IDEATION THROUGH PRODUCTION, WE ARE A ONE-STOP POWERHOUSE.
        </p>

        <PrimaryButton
          text={"MORE ABOUT US"}
          size={"1.1rem"}
          scale={1.8}
          to={"/about"}
        />
      </div>

      <div className={styles.reelContainer}>
        <p className={styles.reelText}>REEL</p>

        <div className={styles.buttonContainer}>
          <SecondaryButton
            text={"OUR WORK"}
            size={"1.1rem"}
            scale={1.8}
            to={"/work"}
          />
        </div>

        <div className={styles.reelVideo}>
          <video autoPlay loop muted>
            <source
              src={
                "https://res.cloudinary.com/fenkratos/video/upload/v1667063996/Nafta/FARDO_nbcvcy.mp4"
              }
              type="video/mp4"
            />
          </video>
        </div>
      </div>

      <Marquee gradient={false} className={styles.marquee} speed={100}>
        <p>
          STED SEÑALEMELO - / - 1915 - / - INVISIBLE - / - PESCADO RABIOSO - / -
          LA MÁQUINA DE HACER PÁJAROS - / - SERÚ GIRÁN - / - NAFTA - / - PAZ
          CARRARA - / - DAUGHTER - / - MEN I TRUST - / - JONATHAN MORALI - / -
          FIN DEL MUNDO - / - LUCY PATANÉ - / - U
        </p>
      </Marquee>
      <div className={styles.otherContainer}>
        <div className={styles.otherContainerInner}>
          <div className={styles.titleBox}>
            <p className={styles.beThe}>BE THE</p>
            <p className={styles.change}>CHANGE</p>
          </div>

          <div className={styles.line}></div>

          <div className={styles.press}>
            <div className={styles.pressText}>
              SOMETIMES, WE GET SOME BUZZ IN THE PRESS.
            </div>

            <div className={styles.pressButtons}>
              <PrimaryButton
                text={"ABOUT"}
                size={"1.1rem"}
                scale={1.8}
                to={"/about"}
              />
              <PrimaryButton
                text={"WORK"}
                size={"1.1rem"}
                scale={1.8}
                to={"/work"}
              />
            </div>
          </div>
        </div>
      </div>

      {/* <video
        preload
        tabindex="-1"
        loop
        src="blob:https://vimeo.com/b35a586d-0efb-4613-9954-2e3566c5fe14"
        style
      ></video> */}
    </div>
  );
};

export default Home;
